#!/bin/sh

# Call with direction [west, south, north, or east] from sxhkd
# If in vim or tmux, forward ctrl-[h, j, k, l], otherwise tell bspwm to focus window in given direction

window=$(xdotool getwindowfocus getwindowname)
window_grep=$(echo "$window" | grep -iE "(^|\s+)(n?vim|tmux(\sa)?)$" -)
if [ -n "${window_grep}" ]; then
	case "$1" in
	west)
		keysym="h"
		;;
	south)
		keysym="j"
		;;
	north)
		keysym="k"
		;;
	east)
		keysym="l"
		;;
	esac

	xdotool keyup "${keysym}" key --clearmodifiers "control+${keysym}"
else
	bspc node -f $1
fi
